language: c
os:
- linux
- osx
dist: xenial
# osx_image: xcode6.4
env:
  global:
  - secure: L+Yqd1nmMuQtCDKbhFPpfKiO1dPwH9J4jcdq6KW3vMixlFYs2546ZxhFaDXVgMXogVziq1FcSrNspaPxn0Zxk1ZuUAeFYU+gVp8/jqZGnkTL4UORMk0hHX6EwFNoUJl9LxpmO3140S67td14U0vBz8dOh9oeNui+VrMJn7NGlpI=
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl -L https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
  else
    curl -L https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
  fi
- ./bin/micromamba shell init -s bash -p ~/micromamba
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    source $HOME/.bash_profile
  else
    source $HOME/.bashrc
  fi
- micromamba activate
- micromamba install mamba --yes -c conda-forge
install:
- mamba install cmake c-compiler pkg-config glib -c conda-forge --yes
script:
- |
  mkdir _build && cd _build
  cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Release
  make -j$CPU_COUNT all install
  make test
- ew/utils/utils-test-io --verbose
- sedflux -h
